[package]
name = "diving"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
chrono = "0.4.23"
libflate = "1.2.0"
lru = "0.9.0"
once_cell = "1.17.0"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
snafu = "0.7.4"
tar = "0.4.38"
tokio = { version = "1.24.1", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }

