[package]
name = "diving"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.6"
axum-client-ip = "0.4.0"
bytes = "1.3.0"
bytesize = "1.1.0"
chrono = "0.4.23"
clap = { version = "4.1.4", features = ["derive"] }
config = "0.13.3"
crossterm = "0.25.0"
futures = "0.3.26"
glob = "0.3.1"
home = "0.5.4"
http = "0.2.8"
humantime = "2.1.0"
libflate = "1.2.0"
lru = "0.9.0"
once_cell = "1.17.0"
pad = "0.1.6"
regex = "1.7.1"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_repr = "0.1.10"
snafu = "0.7.4"
tar = "0.4.38"
tokio = { version = "1.24.1", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "fs"] }
tokio-cron-scheduler = "0.9.4"
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tui = "0.19.0"
unicode-width = "0.1.10"
unix_mode = "0.1.3"
zstd = "0.12.3"

[profile.release]
strip = true 
lto = true
