[package]
name = "diving"
version = "0.4.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
axum-client-ip = "0.4.1"
bytes = "1.4.0"
bytesize = "1.2.0"
chrono = "0.4.26"
clap = { version = "4.3.5", features = ["derive"] }
config = "0.13.3"
crossterm = "0.26.1"
futures = "0.3.28"
glob = "0.3.1"
hex = "0.4.3"
home = "0.5.5"
http = "0.2.9"
humantime = "2.1.0"
libflate = "1.3.0"
lru = "0.10.0"
mime = "0.3.17"
mime_guess = "2.0.4"
nanoid = "0.4.0"
once_cell = "1.18.0"
pad = "0.1.6"
regex = "1.8.4"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "json"] }
rust-embed = { version = "6.7.0", features = ["compression", "mime-guess"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
serde_repr = "0.1.10"
snafu = "0.7.4"
substring = "1.4.5"
tar = "0.4.38"
time = "0.3.22"
tokio = { version = "1.28.2", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "fs"] }
tokio-cron-scheduler = "0.9.4"
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [ "local-time"] }
tui = "0.19.0"
unicode-width = "0.1.10"
unix_mode = "0.1.3"
zstd = "0.12.3"

[profile.release]
strip = true 
lto = true
