[package]
name = "diving"
version = "0.6.5"
authors = ["Tree Xie <tree.xie@outlook.com>"]
edition = "2021"
keywords = ["diving", "image", "dive"]
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
axum-client-ip = "0.5.1"
bytes = "1.5.0"
bytesize = { version = "1.3.0", features = ["serde"] }
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
colored = "2.1.0"
config = "0.14.0"
crossterm = "0.27.0"
futures = "0.3.30"
glob = "0.3.1"
hex = "0.4.3"
home = "0.5.9"
http = "1.1.0"
humantime = "2.1.0"
libflate = "2.0.0"
lru = "0.12.3"
mime = "0.3.17"
mime_guess = "2.0.4"
nanoid = "0.4.0"
once_cell = "1.19.0"
pad = "0.1.6"
ratatui = "0.25.0"
regex = "1.10.3"
reqwest = { version = "0.12.0", default-features = false, features = [
    "rustls-tls",
    "json",
] }
rust-embed = { version = "8.3.0", features = ["compression", "mime-guess"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_repr = "0.1.18"
signal-hook = { version = "0.3.17", default-features = false }
signal-hook-registry = "1.4.1"
snafu = "0.8.2"
substring = "1.4.5"
tar = "0.4.40"
tempfile = "3.10.1"
time = "0.3.34"
tokio = { version = "1.36.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
    "fs",
] }
tokio-cron-scheduler = "0.10.0"
tower = { version = "0.4.13", features = ["timeout"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }
unicode-width = "0.1.11"
unix_mode = "0.1.4"
zstd = "0.13.0"

[profile.release]
codegen-units = 1
lto = true
