[package]
name = "diving"
version = "0.5.10"
authors = ["Tree Xie <tree.xie@outlook.com>"]
edition = "2021"
keywords = ["diving", "image", "dive"]
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.1"
axum-client-ip = "0.5.0"
bytes = "1.5.0"
bytesize = "1.3.0"
chrono = "0.4.31"
clap = { version = "4.4.10", features = ["derive"] }
config = "0.13.4"
crossterm = "0.27.0"
futures = "0.3.29"
glob = "0.3.1"
hex = "0.4.3"
home = "0.5.5"
http = "1.0.0"
humantime = "2.1.0"
libflate = "2.0.0"
lru = "0.12.1"
mime = "0.3.17"
mime_guess = "2.0.4"
nanoid = "0.4.0"
once_cell = "1.18.0"
pad = "0.1.6"
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = ["rustls-tls", "json"] }
rust-embed = { version = "8.0.0", features = ["compression", "mime-guess"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_repr = "0.1.17"
signal-hook = { version = "0.3.17", default-features = false }
signal-hook-registry = "1.4.1"
snafu = "0.7.5"
substring = "1.4.5"
tar = "0.4.40"
tempfile = "3.8.1"
time = "0.3.30"
tokio = { version = "1.34.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "fs"] }
tokio-cron-scheduler = "0.9.4"
tower = { version = "0.4.13", features = ["timeout"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "local-time"] }
tui = "0.19.0"
unicode-width = "0.1.11"
unix_mode = "0.1.4"
zstd = "0.13.0"

[profile.release]
codegen-units = 1
lto = true
